"""Operational services for MTF Lab.

This package deliberately contains no market-specific calculations.  It stores
the observations produced by the core, evaluates virtual outcomes using an
explicit data contract, and exposes reporting/CLI/UI adapters.  The public
classes accept ordinary mappings as well as dataclass-like objects so that the
core can evolve without making persistence a second implementation of it.
"""

from .backtest import BacktestResult, BacktestRunner, PortfolioResult, VariantSpec
from .cfd_simulation import (
    CFDConfig,
    CFDQuote,
    CFDReplayResult,
    CFDSignal,
    CFDSimulationError,
    CFDSimulator,
    CFDTrade,
    Direction,
    ForexCFDConfig,
    ForexCFDQuote,
    ForexCFDSignal,
    ForexCFDSimulator,
    ForexCFDTrade,
    TradeState,
    known_fixture_eurusd_long,
)
from .ctrader_activation import (
    AccountDiscovery,
    ActivationMode,
    ActivationProfile,
    ActivationState,
    ActivationStatus,
    BrokerAccount,
    LoopbackOAuthAssistant,
    OAuthAppConfig,
    OAuthAttempt,
    OAuthAttemptPhase,
    OAuthAttemptStore,
    OAuthTokenPayload,
    SecureTokenStore,
    TokenLease,
    TokenMetadata,
    UnsafeTokenStore,
    build_authorization_url,
    evaluate_activation,
    exchange_authorization_code,
    open_authorization_browser,
    parse_callback_uri,
    record_account_discovery,
    refresh_access_token,
    select_demo_account,
    select_discovered_demo_account,
)
from .ctrader_demo import run_ctrader_fixture
from .ctrader_demo_transport import (
    DEMO_PROTOBUF_ENDPOINT,
    LIVE_PROTOBUF_ENDPOINT,
    VOLUME_SCALE,
    CTraderDemoTransport,
    CTraderDemoTransportConfig,
    CTraderOfficialDemoTransport,
    OfficialCorrelationError,
    OfficialGateway,
    OfficialMessageError,
    OfficialSDKUnavailable,
    OfficialTransportError,
    ServerAccountObservation,
    load_official_proto,
)
from .ctrader_executor import (
    CTraderDemoExecutor,
    DemoAccount,
    DemoTransport,
    ExecutionEvent,
    ExecutionIntent,
    ExecutionPolicy,
    Fill,
    IntentStore,
    JsonlIntentStore,
    MemoryIntentStore,
    OrderResult,
    OrderSnapshot,
    OrderState,
    Position,
    Quote,
    Side,
    verify_demo_account,
)
from .ctrader_history_export import (
    BoundedHistorySelection,
    HistoryCaptureError,
    select_bounded_history_window,
)
from .persistence import SQLiteStore
from .reporting import ReportBuilder
from .simulation import (
    DirectionalEvaluator,
    EvaluationSpec,
    Outcome,
    VirtualContract,
    VirtualContractSimulator,
)

__all__ = [
    "BacktestResult",
    "BacktestRunner",
    "PortfolioResult",
    "DirectionalEvaluator",
    "EvaluationSpec",
    "Outcome",
    "ReportBuilder",
    "SQLiteStore",
    "VariantSpec",
    "VirtualContract",
    "VirtualContractSimulator",
    "CFDConfig",
    "CFDQuote",
    "CFDReplayResult",
    "CFDSignal",
    "CFDSimulationError",
    "CFDSimulator",
    "CFDTrade",
    "Direction",
    "TradeState",
    "ForexCFDConfig",
    "ForexCFDQuote",
    "ForexCFDSignal",
    "ForexCFDSimulator",
    "ForexCFDTrade",
    "known_fixture_eurusd_long",
    "BoundedHistorySelection",
    "HistoryCaptureError",
    "select_bounded_history_window",
    "run_ctrader_fixture",
    "CTraderDemoTransport",
    "CTraderOfficialDemoTransport",
    "CTraderDemoTransportConfig",
    "DEMO_PROTOBUF_ENDPOINT",
    "LIVE_PROTOBUF_ENDPOINT",
    "ServerAccountObservation",
    "OfficialCorrelationError",
    "OfficialGateway",
    "OfficialMessageError",
    "OfficialSDKUnavailable",
    "OfficialTransportError",
    "VOLUME_SCALE",
    "load_official_proto",
    "CTraderDemoExecutor",
    "DemoAccount",
    "DemoTransport",
    "ExecutionPolicy",
    "ExecutionIntent",
    "ExecutionEvent",
    "Fill",
    "IntentStore",
    "MemoryIntentStore",
    "JsonlIntentStore",
    "OrderResult",
    "OrderSnapshot",
    "OrderState",
    "Position",
    "Quote",
    "Side",
    "verify_demo_account",
    "ActivationProfile",
    "ActivationMode",
    "ActivationState",
    "ActivationStatus",
    "BrokerAccount",
    "OAuthAppConfig",
    "OAuthTokenPayload",
    "SecureTokenStore",
    "TokenLease",
    "TokenMetadata",
    "AccountDiscovery",
    "LoopbackOAuthAssistant",
    "OAuthAttempt",
    "OAuthAttemptPhase",
    "OAuthAttemptStore",
    "UnsafeTokenStore",
    "build_authorization_url",
    "open_authorization_browser",
    "parse_callback_uri",
    "exchange_authorization_code",
    "refresh_access_token",
    "evaluate_activation",
    "record_account_discovery",
    "select_demo_account",
    "select_discovered_demo_account",
]

# Pipeline application services are imported from mtf_lab.ops.ctrader_pipeline.
# No package-level re-export: runtime -> persistence must not import runtime again.
